/** Single source of truth for site-wide SEO constants. */
export const SITE = {
  name: "Israel Menyaga",
  shortName: "MIE Portfolio",
  url: "https://israelm.site",
  locale: "en_US",
  language: "en",
  tagline: "Next.js · Nuxt · React · TypeScript · SaaS",
  defaultTitle:
    "Israel Enyo Menyaga — Senior Software Engineer & CTO | Next.js, Nuxt, React",
  defaultDescription:
    "Senior Software Engineer and technical leader. CTO at Belsoft Systems (BelCore, BelPower); shipped SaaS with Next.js, Nuxt, Vue, and React across fintech, HR, and healthcare. Performance, payments, analytics, and freelance delivery from Figma to production.",
  email: "israelvictor126@gmail.com",
  phone: "+2349137437424",
  twitter: "@M_I_E_CODE",
  linkedIn: "https://www.linkedin.com/in/israelmenyaga",
  github: "https://github.com/MIE-CODE",
  cvPath: "/cv/Israel_menyaga_cv.pdf",
  person: {
    givenName: "Israel",
    familyName: "Menyaga",
    fullName: "Israel Enyo Menyaga",
    alternateName: "Menyaga Enyo Israel",
    jobTitle: "Senior Software Engineer",
    role: "CTO & Full Stack Engineer",
  },
  keywords: [
    "Israel Menyaga",
    "Menyaga Enyo Israel",
    "Senior Software Engineer",
    "Full Stack Developer",
    "Next.js Developer",
    "Nuxt Developer",
    "React Developer",
    "Vue Developer",
    "TypeScript Developer",
    "CTO",
    "Technical Leadership",
    "SaaS Development",
    "Fintech Developer",
    "Belsoft Systems",
    "BelCore",
    "BelPower",
    "True Perk",
    "SparkPay",
    "Blivap",
    "Paystack",
    "Performance Optimization",
    "Core Web Vitals",
    "GSAP",
    "PostHog",
    "Google Analytics",
    "Web Developer Portfolio",
    "Freelance Developer Nigeria",
    "MIE",
    "M_I_E_CODE",
  ],
  /** Static fallback when dynamic OG is unavailable */
  staticOgImage: "/og-image.svg",
  twitterImage: "/twitter-image.svg",
  themeColor: "#5b82a8",
} as const;
