/**
 * Site-wide SEO constants — single source of truth for metadata, JSON-LD, and sitemap.
 * OG assets: `public/og-image.svg` + `og-image.png` (generated via `yarn og:generate`).
 */
export const SITE = {
  name: "Israel Enyo Menyaga",
  shortName: "Israel Enyo Menyaga",
  alternateNames: ["Israel Menyaga", "MIE", "MIE-CODE"] as const,
  url: "https://israelm.site",
  locale: "en_US",
  language: "en",
  location: "Remote / Nigeria",
  /** ~155 characters — root & OG description */
  defaultDescription:
    "Israel Enyo Menyaga (MIE), Senior Software Engineer & CTO: React, Next.js, TypeScript, AI integration, fintech & healthcare. Founder of Blivap blood donation platform.",
  defaultTitle: "Israel Enyo Menyaga (MIE) | Senior Software Engineer & CTO",
  tagline: "React · Next.js · TypeScript · AI · Fintech · Healthcare",
  email: "israelmenyaga@gmail.com",
  phone: "+2349137437424",
  twitter: "@israelmenyaga",
  twitterHandle: "israelmenyaga",
  linkedIn: "https://linkedin.com/in/israelmenyaga",
  github: "https://github.com/MIE-CODE",
  blivap: "https://blivap.com",
  cvPath: "/cv/Israel_menyaga_cv.pdf",
  /** Primary static OG asset — create 1200×630 PNG at public/og-image.png */
  ogImage: "/og-image.png",
  ogImageAlt:
    "Israel Enyo Menyaga (MIE) — Senior Software Engineer, CTO & Founder of Blivap",
  staticOgImageFallback: "/og-image.svg",
  twitterImage: "/og-image.png",
  themeColor: "#5b82a8",
  person: {
    givenName: "Israel",
    familyName: "Menyaga",
    fullName: "Israel Enyo Menyaga",
    alternateName: ["Israel Menyaga", "MIE", "MIE-CODE"] as const,
    jobTitle: "Senior Software Engineer & CTO",
    role: "Senior Software Engineer & CTO",
  },
  organizations: {
    belsoft: "Belsoft Systems",
    truperk: "Truperk",
  },
  keywords: [
    "Israel Enyo Menyaga",
    "Israel Menyaga",
    "israelmenyaga",
    "MIE developer",
    "MIE software engineer",
    "MIE-CODE",
    "MIE coder",
    "Israel Menyaga developer",
    "Israel Menyaga software engineer",
    "Israel Menyaga CTO",
    "Israel Menyaga React developer",
    "Israel Menyaga Next.js",
    "Israel Enyo Menyaga engineer",
    "Blivap founder",
    "Blivap developer",
    "blivap.com creator",
    "blood donation platform developer",
    "Blivap Israel Menyaga",
    "Senior Frontend Engineer Nigeria",
    "React TypeScript developer Nigeria",
    "Next.js developer portfolio",
    "AI integration engineer",
    "Fintech frontend developer",
    "NestJS developer",
    "Full stack engineer Nigeria",
    "Belsoft Systems CTO",
    "Truperk engineer",
    "MIE portfolio",
  ],
} as const;
